export async function downloadLetterAsPDF(
  letterText: string,
  subject: string,
  applicationType: string
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 22;
  const usableWidth = pageWidth - margin * 2;

  // Background
  doc.setFillColor(252, 251, 248);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Top gold bar
  doc.setFillColor(201, 149, 58);
  doc.rect(0, 0, pageWidth, 3, "F");

  // Header
  const startY = 18;
  doc.setFontSize(7.5);
  doc.setTextColor(160, 130, 80);
  doc.setFont("helvetica", "bold");
  doc.text(applicationType.toUpperCase(), margin, startY);

  // Divider
  doc.setDrawColor(201, 149, 58);
  doc.setLineWidth(0.4);
  doc.line(margin, startY + 5, pageWidth - margin, startY + 5);

  // Content
  doc.setFont("times", "normal");
  doc.setFontSize(11.5);
  doc.setTextColor(26, 23, 20);

  const lines = letterText.split("\n");
  let y = startY + 14;
  const lineHeight = 6.5;

  for (const rawLine of lines) {
    const wrappedLines = rawLine.trim() === "" ? [""] : doc.splitTextToSize(rawLine, usableWidth);

    for (const segment of wrappedLines) {
      if (y > pageHeight - margin - 10) {
        doc.addPage();
        doc.setFillColor(252, 251, 248);
        doc.rect(0, 0, pageWidth, pageHeight, "F");
        doc.setFillColor(201, 149, 58);
        doc.rect(0, 0, pageWidth, 3, "F");
        y = margin + 6;
      }

      const isHeader = /^(dear|to:|from:|date:|re:|subject:|regards|sincerely|yours)/i.test(segment.trim());
      doc.setFont("times", isHeader ? "bold" : "normal");
      doc.text(segment, margin, y);
      y += lineHeight;
    }

    if (rawLine.trim() === "") y += 1;
  }

  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(180, 165, 140);
    doc.setFont("helvetica", "normal");
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: "center" });
    doc.text("Generated by Quill AI", pageWidth - margin, pageHeight - 8, { align: "right" });
  }

  const filename = `${applicationType.toLowerCase().replace(/\s+/g, "-")}-${(subject || "letter").toLowerCase().replace(/\s+/g, "-").slice(0, 30)}.pdf`;
  doc.save(filename);
}
